apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  # tells deployment how to find all the pods it's going to create
  selector:
    matchLabels:
      app: auth
  # how to create each pod the deployment will create
  template:
    metadata:
      labels:
        app: auth
    # tells the pod how to behave
    spec:
      containers:
        - name: auth
          image: dozer1234/auth
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
---
# default type is ClusterIP so we didn't need to add it to this service (since it's a cluster IP service)

apiVersion: v1
kind: Service
metadata:
  name: auth-srv
# tells service how to behave
spec:
  # how to find the pods to govern access to
  selector:
    # find all pods with label -> app:auth
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
